In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("London Housing Data.csv")

In [3]:
df.shape

(13549, 6)

In [4]:
df

,date,area,average_price,code,houses_sold,no_of_crimes
0,1/1/1995,city of london,91449,E09000001,17.0,NaN
1,2/1/1995,city of london,82203,E09000001,7.0,NaN
2,3/1/1995,city of london,79121,E09000001,14.0,NaN
3,4/1/1995,city of london,77101,E09000001,7.0,NaN
4,5/1/1995,city of london,84409,E09000001,10.0,NaN
...,...,...,...,...,...,...
13544,9/1/2019,england,249942,E92000001,64605.0,NaN
13545,10/1/2019,england,249376,E92000001,68677.0,NaN
13546,11/1/2019,england,248515,E92000001,67814.0,NaN
13547,12/1/2019,england,250410,E92000001,NaN,NaN
13548,1/1/2020,england,247355,E92000001,NaN,NaN

In [5]:
df.head()

,date,area,average_price,code,houses_sold,no_of_crimes
0,1/1/1995,city of london,91449,E09000001,17.0,NaN
1,2/1/1995,city of london,82203,E09000001,7.0,NaN
2,3/1/1995,city of london,79121,E09000001,14.0,NaN
3,4/1/1995,city of london,77101,E09000001,7.0,NaN
4,5/1/1995,city of london,84409,E09000001,10.0,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13549 entries, 0 to 13548
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           13549 non-null  object
 1   area           13549 non-null  object
 2   average_price  13549 non-null  int64
 3   code           13549 non-null  object
 4   houses_sold    13455 non-null  float64
 5   no_of_crimes   7439 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 635.2+ KB

In [7]:
df.isnull().sum()

date                0
area                0
average_price       0
code                0
houses_sold        94
no_of_crimes     6110
dtype: int64

In [8]:
df.fillna(df["houses_sold"].mean())

,date,area,average_price,code,houses_sold,no_of_crimes
0,1/1/1995,city of london,91449,E09000001,17.000000,3893.994129
1,2/1/1995,city of london,82203,E09000001,7.000000,3893.994129
2,3/1/1995,city of london,79121,E09000001,14.000000,3893.994129
3,4/1/1995,city of london,77101,E09000001,7.000000,3893.994129
4,5/1/1995,city of london,84409,E09000001,10.000000,3893.994129
...,...,...,...,...,...,...
13544,9/1/2019,england,249942,E92000001,64605.000000,3893.994129
13545,10/1/2019,england,249376,E92000001,68677.000000,3893.994129
13546,11/1/2019,england,248515,E92000001,67814.000000,3893.994129
13547,12/1/2019,england,250410,E92000001,3893.994129,3893.994129
13548,1/1/2020,england,247355,E92000001,3893.994129,3893.994129

In [9]:
df

,date,area,average_price,code,houses_sold,no_of_crimes
0,1/1/1995,city of london,91449,E09000001,17.0,NaN
1,2/1/1995,city of london,82203,E09000001,7.0,NaN
2,3/1/1995,city of london,79121,E09000001,14.0,NaN
3,4/1/1995,city of london,77101,E09000001,7.0,NaN
4,5/1/1995,city of london,84409,E09000001,10.0,NaN
...,...,...,...,...,...,...
13544,9/1/2019,england,249942,E92000001,64605.0,NaN
13545,10/1/2019,england,249376,E92000001,68677.0,NaN
13546,11/1/2019,england,248515,E92000001,67814.0,NaN
13547,12/1/2019,england,250410,E92000001,NaN,NaN
13548,1/1/2020,england,247355,E92000001,NaN,NaN

In [10]:
df.tail()

            date     area  average_price       code  houses_sold  no_of_crimes
13544   9/1/2019  england         249942  E92000001      64605.0           NaN
13545  10/1/2019  england         249376  E92000001      68677.0           NaN
13546  11/1/2019  england         248515  E92000001      67814.0           NaN
13547  12/1/2019  england         250410  E92000001          NaN           NaN
13548   1/1/2020  england         247355  E92000001          NaN           NaN

**Basic**

In [11]:
# 1.Display first 10 rows and last 5 rows of the dataset
df.head(10)
df.tail()

            date     area  average_price       code  houses_sold  no_of_crimes
13544   9/1/2019  england         249942  E92000001      64605.0           NaN
13545  10/1/2019  england         249376  E92000001      68677.0           NaN
13546  11/1/2019  england         248515  E92000001      67814.0           NaN
13547  12/1/2019  england         250410  E92000001          NaN           NaN
13548   1/1/2020  england         247355  E92000001          NaN           NaN

In [12]:
# Check the shape, datatypes and basic info of dataset
df.shape
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13549 entries, 0 to 13548
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           13549 non-null  object
 1   area           13549 non-null  object
 2   average_price  13549 non-null  int64
 3   code           13549 non-null  object
 4   houses_sold    13455 non-null  float64
 5   no_of_crimes   7439 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 635.2+ KB

In [13]:
# Find total number of null values in each column
df.isnull().sum()

date                0
area                0
average_price       0
code                0
houses_sold        94
no_of_crimes     6110
dtype: int64

In [14]:
# Find how many unique areas are there
pd.unique(df["area"])
df["area"].nunique()

45

In [15]:
# Find the average price of all houses in the dataset
df["average_price"].mean()

263519.68433094694

**Filtering & Sorting**

In [16]:
# Filter all rows where average_price is greater than 500000
df[df["average_price"]>500000]

,date,area,average_price,code,houses_sold,no_of_crimes
193,2/1/2011,city of london,504009,E09000001,12.0,NaN
195,4/1/2011,city of london,516319,E09000001,21.0,NaN
204,1/1/2012,city of london,525723,E09000001,11.0,NaN
205,2/1/2012,city of london,510537,E09000001,17.0,NaN
206,3/1/2012,city of london,527408,E09000001,9.0,NaN
...,...,...,...,...,...,...
10234,9/1/2019,inner london,577852,E13000001,2370.0,NaN
10235,10/1/2019,inner london,575198,E13000001,2373.0,NaN
10236,11/1/2019,inner london,574539,E13000001,2226.0,NaN
10237,12/1/2019,inner london,575511,E13000001,NaN,NaN
10238,1/1/2020,inner london,581939,E13000001,NaN,NaN

In [17]:
# Find all data for "barnet" area only
df[df["area"]=="barnet"]

          date    area  average_price       code  houses_sold  no_of_crimes
602   1/1/1995  barnet          93285  E09000003        332.0           NaN
603   2/1/1995  barnet          93190  E09000003        327.0           NaN
604   3/1/1995  barnet          92248  E09000003        384.0           NaN
605   4/1/1995  barnet          90763  E09000003        304.0           NaN
606   5/1/1995  barnet          90258  E09000003        393.0           NaN
..         ...     ...            ...        ...          ...           ...
898   9/1/2019  barnet         527115  E09000003        239.0        2604.0
899  10/1/2019  barnet         525739  E09000003        262.0        2625.0
900  11/1/2019  barnet         523582  E09000003        253.0        2827.0
901  12/1/2019  barnet         517986  E09000003          NaN        2603.0
902   1/1/2020  barnet         520682  E09000003          NaN        2621.0

[301 rows x 6 columns]

In [18]:
# Sort the dataset by average_price in descending order
df.sort_values(by="average_price",ascending=False)

,date,area,average_price,code,houses_sold,no_of_crimes
6001,1/1/2018,kensington and chelsea,1463378,E09000020,129.0,1737.0
6008,8/1/2018,kensington and chelsea,1418032,E09000020,103.0,2339.0
5990,2/1/2017,kensington and chelsea,1412255,E09000020,109.0,1367.0
5992,4/1/2017,kensington and chelsea,1399839,E09000020,124.0,1723.0
5989,1/1/2017,kensington and chelsea,1394421,E09000020,136.0,1534.0
...,...,...,...,...,...,...
10550,11/1/1995,north east,41728,E12000001,2620.0,NaN
10549,10/1/1995,north east,41688,E12000001,2674.0,NaN
10555,4/1/1996,north east,41588,E12000001,2604.0,NaN
10552,1/1/1996,north east,40790,E12000001,2020.0,NaN
10553,2/1/1996,north east,40722,E12000001,2113.0,NaN

In [19]:
# Find the area with the highest average price
df[df["average_price"]==df["average_price"].max()]["area"]

6001    kensington and chelsea
Name: area, dtype: object

In [20]:
# Find rows where no_of_crimes is null
df["no_of_crimes"].isnull().sum()

6110

In [21]:
# Find mean average price for each area using groupby
df.groupby("area")["average_price"].mean()

area
barking and dagenham      159852.930233
barnet                    304991.089701
bexley                    189570.737542
brent                     270291.252492
bromley                   254160.621262
camden                    467500.910299
city of london            423942.584718
croydon                   209349.671096
ealing                    274537.322259
east midlands             121649.890365
east of england           171182.229236
enfield                   223130.629139
england                   153068.843854
greenwich                 213056.471761
hackney                   284985.331126
hammersmith and fulham    443791.860465
haringey                  292969.634551
harrow                    269233.102990
havering                  205026.664452
hillingdon                233404.930233
hounslow                  235965.421927
inner london              314994.421927
islington                 365187.717608
kensington and chelsea    742060.368771
kingston upon thames      281688.425249
lambeth                   279398.428571
lewisham                  216601.893688
london                    265517.425249
merton                    281298.767442
newham                    195646.066445
north east                 97041.076412
north west                108789.574751
outer london              239366.019934
redbridge                 235093.116279
richmond upon thames      382615.960133
south east                196067.076159
south west                163353.252492
southwark                 275004.581395
sutton                    217273.445183
tower hamlets             257253.016556
waltham forest            220395.159468
wandsworth                342304.199336
west midlands             127102.840532
westminster               543865.936877
yorks and the humber      109112.677741
Name: average_price, dtype: float64

In [22]:
df.columns

Index(['date', 'area', 'average_price', 'code', 'houses_sold', 'no_of_crimes'], dtype='object')

In [23]:
# Find total houses sold per area
df.groupby("area")["houses_sold"].sum()

area
barking and dagenham         59498.0
barnet                      133648.0
bexley                       97351.0
brent                        81613.0
bromley                     148516.0
camden                       74362.0
city of london                7586.0
croydon                     145906.0
ealing                      110042.0
east midlands              2033724.0
east of england            2809800.0
enfield                     115249.0
england                   23077637.0
greenwich                    94126.0
hackney                      65356.0
hammersmith and fulham       75518.0
haringey                     81162.0
harrow                       78921.0
havering                     95135.0
hillingdon                  104721.0
hounslow                     85472.0
inner london               1233831.0
islington                    68271.0
kensington and chelsea       77128.0
kingston upon thames         75627.0
lambeth                     117953.0
lewisham                    108123.0
london                     3134378.0
merton                       87262.0
newham                       86236.0
north east                 1033675.0
north west                 2895280.0
outer london               1897009.0
redbridge                   102511.0
richmond upon thames         97074.0
south east                 4195116.0
south west                 2639661.0
southwark                    99714.0
sutton                       91399.0
tower hamlets               101857.0
waltham forest               92938.0
wandsworth                  163871.0
west midlands              2128978.0
westminster                 106694.0
yorks and the humber       2183762.0
Name: houses_sold, dtype: float64

In [24]:
# Which area has the most houses sold overall?
total=df.groupby("area")["houses_sold"].sum()

In [25]:
total.idxmax()

'england'

In [26]:
# Find minimum and maximum average price for each area
df.groupby("area")["average_price"].agg(["max","min"])

                            max     min
area
barking and dagenham     305882   50460
barnet                   549401   90107
bexley                   347531   63723
brent                    519754   71307
bromley                  449293   81124
camden                   881212  115419
city of london           939912   77101
croydon                  378859   68006
ealing                   489687   79272
east midlands            196534   44506
east of england          294035   55033
enfield                  404393   70631
england                  250410   52333
greenwich                408407   60993
hackney                  575846   61297
hammersmith and fulham   781175  120636
haringey                 578728   76288
harrow                   479341   82054
havering                 373762   66182
hillingdon               419452   71760
hounslow                 413672   71052
inner london             593486   75886
islington                677798   89406
kensington and chelsea  1463378  182345
kingston upon thames     511260   80876
lambeth                  532804   65382
lewisham                 423063   57700
london                   488527   72778
merton                   534091   79569
newham                   371678   53154
north east               139400   40722
north west               167430   42599
outer london             432669   72592
redbridge                430708   72142
richmond upon thames     682854  106875
south east               328061   63715
south west               259145   53081
southwark                535685   60886
sutton                   387410   69291
tower hamlets            470788   59865
waltham forest           452299   60252
wandsworth               633826   86518
west midlands            201447   47952
westminster             1117408  131468
yorks and the humber     166932   43461